version: "3.8"
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=${JWT_SECRET}
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://ollama:11434
      - OLLAMA_MODEL=llama3:8b-instruct-q5_1
      - OLLAMA_MODEL_TOKEN_LIMIT=2048
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_BASE_PATH=http://ollama:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - CHROMA_ENDPOINT=http://chroma:8000
      - CHROMA_API_HEADER=
      - CHROMA_API_KEY=
      - GENERATE_JWT_SECRET=false
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
    volumes:
      - ./data/storage:/app/server/storage
      - ./data/documents:/app/server/documents
      - ./data/vector-cache:/app/server/storage/vector-cache
      - ./data/chroma:/app/server/storage/vector-db/chroma
    restart: unless-stopped
    depends_on:
      - ollama
      - chroma
    networks:
      - anythingllm-network

  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_GPU_OVERHEAD=200
      - OLLAMA_FLASH_ATTENTION=true
    ports:
      - "11434:11434"
    volumes:
      - ./scripts:/scripts
      - ./data/ollama:/root/.ollama
    entrypoint: ["/bin/bash", "/scripts/init-ollama.sh"]
    restart: unless-stopped
    networks:
      - anythingllm-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./data/chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    ports:
      - "8000:8000"
    networks:
      - anythingllm-network
    restart: unless-stopped

networks:
  anythingllm-network:
    driver: bridge
